routes/web.php
<?php

Route::get('pruebas', function () {
 
});
// vista comun
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'DashboardController@index');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::resource('pregunta', 'PreguntaController')->except([
    'destroy'
]);

Route::get('preguntas/{id}', 'PreguntaController@eliminar')->name('preguntas.eliminar');

// Route::delete('/preguntas/{id}', 'PreguntaController@eliminar')
//     ->where('id', '[0-9]+')
//     ->name('preguntas.eliminar');


Route::get('user/profile/{user}', 'UserController@editProfile')->name('user.edit.profile');;
Route::patch('user/profile/{user}', 'UserController@updateProfile')->name('user.update.profile');;

Route::resource('configurations', 'ConfigurationController');
Route::resource('rols', 'RolController');
Route::resource('users', 'UserController');

Route::get('user/{user}/menu', 'UserController@menu')->name('user.menu');;
Route::patch('user/menu/{user}', 'UserController@menuStore')->name('users.menuStore');


Route::get('option/create/{padre}', 'OptionMenuController@create')->name('option.create');
Route::get('option/orden', 'OptionMenuController@updateOrden')->name('option.order');
Route::get('option/orden', 'OptionMenuController@updateOrden')->name('option.order.store');
Route::resource('options',"OptionMenuController");

Route::get('oauth/client',"UserController@adminOauthClient")->name('oauth.clients');


Route::get('prueba/pdf', function (\App\Extensiones\Fpdf $fpdf) {
    $fpdf->AddPage();
    $fpdf->SetFont('Courier', 'B', 18);
    $fpdf->Cell(50, 25, 'Hello World!');
    $fpdf->Output();
    exit();
})->name('prueba.pdf');

Route::resource('permissions', 'PermissionController');

Route::get('/consulta/respuesta',        'ConsultaController@index')->name('consulta.index');
Route::get('/consulta/respuesta/{id}', 'ConsultaController@stor')->name('consulta.stor');
Route::post('/consulta/respuestas/{id}',  'ConsultaController@store')->name('consultas.store');

Route::get('/consulta/respondidas',     'ConsultaController@edit')->name('consulta.edit');
Route::get('/consulta/cerradas',        'ConsultaController@show')->name('consulta.show');

//consulta/respuesta/{$id}
 

/*

Route::get('/customers', 'CustomerController@index')
->name('customerIndex');
Route::get('/customers/create', 'CustomerController@create')
->name('customerCreate');
Route::post('/customers', 'CustomerController@store')
->name('customerStore');
Route::get('/customers/{customer}', 'CustomerController@show')
->name('customerShow');
Route::get('/customers/{customer}/edit', 'CustomerController@edit')
->name('customerEdit');
Route::put('/customers/{customer}', 'CustomerController@update')
->name('customerUpdate');
Route::delete('/customers/{customer}', 'CustomerController@destroy')
->name('customerDestroy');
*/

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('htmlheader_title')
    Dashboard 
@endsection

@include('layouts.plugins.jquery-ui')

@push('css')
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    {{--<link rel="stylesheet" href="dist/css/adminlte.min.css">--}}
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{asset('plugins/morris/morris.css')}}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.css')}}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{asset('plugins/datepicker/datepicker3.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('plugins/daterangepicker/daterangepicker-bs3.css')}}">


    @endpush

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div><!-- /.col -->
                
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
                 @include('flash::message')
                @include('adminlte-templates::common.errors')

            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                             
                            <!-- <h3>150</h3> -->

                            <h3> {{ $pregunta }} </h3>

                            <p>Total de las consultas</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                        <a href="#" class="small-box-footer"> _ <i class="fa fa-arrow-circle-right"></i> _</a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>{{ $counto }}<sup style="font-size: 20px">ª</sup></h3>

                            <p> Consulatas por responder </p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a href="{{ route('consulta.index') }}" class="small-box-footer"> Link IR <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3> {{ $contestada }}</h3>

                            <p> Consultas respondias  </p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="{{ route('consulta.edit') }}" class="small-box-footer">Link IR <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>

             
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-danger">
                        <div class="inner">
                            <h3> {{ $cerrada }} </h3>

                            <p> Consulta ya Cerradas </p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="{{ route('consulta.show') }}" class="small-box-footer">Link IR <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>
            <!-- /.row -->
            <!-- Main row -->
            <div class="row">
                <!-- Left col -->
                <section class="col-lg-7 connectedSortable">
                    <!-- Custom tabs (Charts with tabs)-->
                   

                    
                </section>
                <!-- /.Left col -->
                <!-- right col (We are only adding the ID to make the widgets sortable)-->
            
                <!-- right col -->
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@push('scripts')

    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>

    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="{{asset('plugins/morris/morris.min.js')}}"></script>
    <!-- Sparkline -->
    <script src="{{asset('plugins/sparkline/jquery.sparkline.min.js')}}"></script>
    <!-- jvectormap -->
    <script src="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
    <script src="{{asset('plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{asset('plugins/knob/jquery.knob.js')}}"></script>

    <!-- daterangepicker -->
    <script src="{{asset('js/moment/moment.min.js')}}"></script>
    <script src="{{asset('js/moment/es.js')}}"></script>
    <script src="{{asset('plugins/daterangepicker/daterangepicker.js')}}"></script>

    <!-- datepicker -->
    <script src="{{asset('plugins/datepicker/bootstrap-datepicker.js')}}"></script>

    <!-- Bootstrap WYSIHTML5 -->
    {{--<script src="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>--}}
    <!-- Slimscroll -->
    <script src="{{asset('plugins/slimScroll/jquery.slimscroll.min.js')}}"></script>
    <!-- FastClick -->
    <script src="{{asset('plugins/fastclick/fastclick.js')}}"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{{asset('js/dashboard.js')}}"></script>
    <!-- AdminLTE for demo purposes -->
    {{--<script src="dist/js/demo.js"></script>--}}
@endpush

resources/views/hindex.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection
@extends('layouts.app')

@section('htmlheader_title')
    Pregunta 
@endsection

@include('layouts.plugins.jquery-ui')

@push('css')
    <!-- Ionicons -->
    <!-- <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"> -->
    <!-- Theme style -->
    {{--<link rel="stylesheet" href="dist/css/adminlte.min.css">--}}
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{asset('plugins/morris/morris.css')}}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.css')}}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{asset('plugins/datepicker/datepicker3.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('plugins/daterangepicker/daterangepicker-bs3.css')}}">


    @endpush

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div>
                <!-- 
                    head de la pag
                 -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">        
                @include('flash::message')
                @include('adminlte-templates::common.errors')
            <div class="row">
                <!-- formulario de la consulta  -->

                <div class="card">
                    <div class="card-body">
                            <form method="POST" action="{{ route('pregunta.store') }}"  role="form">
                                    {{ csrf_field() }}
                            
                                <div class="form-row">

                                    <!-- ('titulo');
                                    ('descripcion'); -->

                                <!-- Username Field -->
                                <div class="form-group col-sm-10">
                                    <label for="pregunta">Pregunta:</label>
                                    <input class="form-control" name="pregunta" placeholder="pregunta de la consulata" type="text" id="pregunta">
                                </div>

                                <!-- Name Field -->
                                <div class="form-group col-sm-10">
                                    <label for="descripcion">descripcion:</label>
                                    <input class="form-control" name="descripcion" placeholder="descripcion de la consulata" type="text" id="descripcion">
                                </div>

                                <!-- Email Field -->
                                <!-- <div class="form-group col-sm-6">
                                    <label for="email">Email:</label>
                                    <input class="form-control" name="email" type="email" id="email">
                                </div> -->

                             

                                    <!-- Submit Field -->
                                    <div class="form-group col-sm-12">

                                        <button type="submit" onclick="this.form.submit(); this.disabled=true;"
                                            class="btn btn-outline-success waves-effect waves-light">Guardar</button>
                                        <a href="{{ route('dashboard') }}"
                                        class="btn btn-outline-default waves-effect waves-light">Cancelar</a>
                                    </div>
                            </div>
                        </form>
                    </div>
                </div>
                
                <!-- formulario de la consulta  -->
        
            </div>

            <div class="table-responsive">
                {!! $dataTable->table(['width' => '100%']) !!}
            </div>


        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@section('scripts')
@include('layouts.datatables_js')
{!! $dataTable->scripts() !!}
<script>
    $(function () {
            var dt = window.LaravelDataTables["dataTableBuilder"];
            
            //Cuando dibuja la tabla
            dt.on( 'draw.dt', function () {
                $(this).addClass('table-sm table-striped table-bordered table-hover');
                $('[data-toggle="tooltip"]').tooltip();
            });
            
        })
        </script>
@endsection
@push('scripts')
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <!-- <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script> -->

    <!-- Morris.js charts -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script> -->
    <script src="{{asset('plugins/morris/morris.min.js')}}"></script>
    <!-- Sparkline -->
    <script src="{{asset('plugins/sparkline/jquery.sparkline.min.js')}}"></script>
    <!-- jvectormap -->
    <script src="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
    <script src="{{asset('plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{asset('plugins/knob/jquery.knob.js')}}"></script>

    <!-- daterangepicker -->
    <script src="{{asset('js/moment/moment.min.js')}}"></script>
    <script src="{{asset('js/moment/es.js')}}"></script>
    <script src="{{asset('plugins/daterangepicker/daterangepicker.js')}}"></script>

    <!-- datepicker -->
    <script src="{{asset('plugins/datepicker/bootstrap-datepicker.js')}}"></script>

    <!-- Bootstrap WYSIHTML5 -->
    {{--<script src="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>--}}
    <!-- Slimscroll -->
    <script src="{{asset('plugins/slimScroll/jquery.slimscroll.min.js')}}"></script>
    <!-- FastClick -->
    <script src="{{asset('plugins/fastclick/fastclick.js')}}"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{{asset('js/dashboard.js')}}"></script>
    <!-- AdminLTE for demo purposes -->
    {{--<script src="dist/js/demo.js"></script>--}}
@endpush

resources/views/pregunta.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection
@extends('layouts.app')

@section('htmlheader_title')
    Pregunta 
@endsection

@include('layouts.plugins.jquery-ui')

@push('css')
    <!-- Ionicons -->
    <!-- <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"> -->
    <!-- Theme style -->
    {{--<link rel="stylesheet" href="dist/css/adminlte.min.css">--}}
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{asset('plugins/morris/morris.css')}}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.css')}}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{asset('plugins/datepicker/datepicker3.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('plugins/daterangepicker/daterangepicker-bs3.css')}}">


    @endpush

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div>
                <!-- 
                    head de la pag
                 -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">        
                @include('flash::message')
                @include('adminlte-templates::common.errors')
            <div class="row">
                <!-- formulario de la consulta  -->

                <div class="card">
                    <div class="card-body">
                            <form method="POST" action="{{ route('pregunta.store') }}"  role="form">
                                    {{ csrf_field() }}
                            
                                <div class="form-row">

                                    <!-- ('titulo');
                                    ('descripcion'); -->

                                <!-- Username Field -->
                                <div class="form-group col-sm-10">
                                    <label for="pregunta">Pregunta:</label>
                                    <input class="form-control" name="pregunta" placeholder="pregunta de la consulata" type="text" id="pregunta">
                                </div>

                                <!-- Name Field -->
                                <div class="form-group col-sm-10">
                                    <label for="descripcion">descripcion:</label>
                                    <input class="form-control" name="descripcion" placeholder="descripcion de la consulata" type="text" id="descripcion">
                                </div>

                                <!-- Email Field -->
                                <!-- <div class="form-group col-sm-6">
                                    <label for="email">Email:</label>
                                    <input class="form-control" name="email" type="email" id="email">
                                </div> -->

                             

                                    <!-- Submit Field -->
                                    <div class="form-group col-sm-12">

                                        <button type="submit" onclick="this.form.submit(); this.disabled=true;"
                                            class="btn btn-outline-success waves-effect waves-light">Guardar</button>
                                        <a href="{{ route('dashboard') }}"
                                        class="btn btn-outline-default waves-effect waves-light">Cancelar</a>
                                    </div>
                            </div>
                        </form>
                    </div>
                </div>
                
                <!-- formulario de la consulta  -->
        
            </div>

            <div class="table-responsive">
                {!! $dataTable->table(['width' => '100%']) !!}
            </div>


        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@section('scripts')
@include('layouts.datatables_js')
{!! $dataTable->scripts() !!}
<script>
    $(function () {
            var dt = window.LaravelDataTables["dataTableBuilder"];
            
            //Cuando dibuja la tabla
            dt.on( 'draw.dt', function () {
                $(this).addClass('table-sm table-striped table-bordered table-hover');
                $('[data-toggle="tooltip"]').tooltip();
            });
            
        })
        </script>
@endsection
@push('scripts')
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <!-- <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script> -->

    <!-- Morris.js charts -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script> -->
    <script src="{{asset('plugins/morris/morris.min.js')}}"></script>
    <!-- Sparkline -->
    <script src="{{asset('plugins/sparkline/jquery.sparkline.min.js')}}"></script>
    <!-- jvectormap -->
    <script src="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
    <script src="{{asset('plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{asset('plugins/knob/jquery.knob.js')}}"></script>

    <!-- daterangepicker -->
    <script src="{{asset('js/moment/moment.min.js')}}"></script>
    <script src="{{asset('js/moment/es.js')}}"></script>
    <script src="{{asset('plugins/daterangepicker/daterangepicker.js')}}"></script>

    <!-- datepicker -->
    <script src="{{asset('plugins/datepicker/bootstrap-datepicker.js')}}"></script>

    <!-- Bootstrap WYSIHTML5 -->
    {{--<script src="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>--}}
    <!-- Slimscroll -->
    <script src="{{asset('plugins/slimScroll/jquery.slimscroll.min.js')}}"></script>
    <!-- FastClick -->
    <script src="{{asset('plugins/fastclick/fastclick.js')}}"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{{asset('js/dashboard.js')}}"></script>
    <!-- AdminLTE for demo purposes -->
    {{--<script src="dist/js/demo.js"></script>--}}
@endpush