routes/web.php
<?php

Route::get('pruebas', function () {
 
});
// vista comun
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'DashboardController@index');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::resource('pregunta', 'PreguntaController')->except([
    'destroy'
]);

Route::get('preguntas/{id}', 'PreguntaController@eliminar')->name('preguntas.eliminar');

// Route::delete('/preguntas/{id}', 'PreguntaController@eliminar')
//     ->where('id', '[0-9]+')
//     ->name('preguntas.eliminar');


Route::get('user/profile/{user}', 'UserController@editProfile')->name('user.edit.profile');;
Route::patch('user/profile/{user}', 'UserController@updateProfile')->name('user.update.profile');;

Route::resource('configurations', 'ConfigurationController');
Route::resource('rols', 'RolController');
Route::resource('users', 'UserController');

Route::get('user/{user}/menu', 'UserController@menu')->name('user.menu');;
Route::patch('user/menu/{user}', 'UserController@menuStore')->name('users.menuStore');


Route::get('option/create/{padre}', 'OptionMenuController@create')->name('option.create');
Route::get('option/orden', 'OptionMenuController@updateOrden')->name('option.order');
Route::get('option/orden', 'OptionMenuController@updateOrden')->name('option.order.store');
Route::resource('options',"OptionMenuController");

Route::get('oauth/client',"UserController@adminOauthClient")->name('oauth.clients');


Route::get('prueba/pdf', function (\App\Extensiones\Fpdf $fpdf) {
    $fpdf->AddPage();
    $fpdf->SetFont('Courier', 'B', 18);
    $fpdf->Cell(50, 25, 'Hello World!');
    $fpdf->Output();
    exit();
})->name('prueba.pdf');

Route::resource('permissions', 'PermissionController');

Route::get('/consulta/respuesta',        'ConsultaController@index')->name('consulta.index');
Route::get('/consulta/respuesta/{id}', 'ConsultaController@stor')->name('consulta.stor');
Route::post('/consulta/respuestas/{id}',  'ConsultaController@store')->name('consultas.store');

Route::get('/consulta/respondidas',     'ConsultaController@edit')->name('consulta.edit');
Route::get('/consulta/cerradas',        'ConsultaController@show')->name('consulta.show');

//consulta/respuesta/{$id}
 

/*

Route::get('/customers', 'CustomerController@index')
->name('customerIndex');
Route::get('/customers/create', 'CustomerController@create')
->name('customerCreate');
Route::post('/customers', 'CustomerController@store')
->name('customerStore');
Route::get('/customers/{customer}', 'CustomerController@show')
->name('customerShow');
Route::get('/customers/{customer}/edit', 'CustomerController@edit')
->name('customerEdit');
Route::put('/customers/{customer}', 'CustomerController@update')
->name('customerUpdate');
Route::delete('/customers/{customer}', 'CustomerController@destroy')
->name('customerDestroy');
*/

app/User.php
<?php

namespace App;

use App\Models\Role;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

/**
 * App\User
 *
 * @property int $id
 * @property string $username
 * @property string $name
 * @property string|null $email
 * @property string $password
 * @property string|null $remember_token
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @property string|null $deleted_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Option[] $opciones
 * @property-read \Illuminate\Database\Eloquent\Collection|Role[] $rols
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Uimage[] $uimages
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Query\Builder|\App\User onlyTrashed()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereUsername($value)
 * @method static \Illuminate\Database\Query\Builder|\App\User withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\User withoutTrashed()
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    use HasRoles;
    use HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username','email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name'     => 'required|max:255',
        'username' => 'sometimes|required|max:255|unique:users',
        'email'    => 'required|email|max:255',
        'password' => 'required|min:6|confirmed',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function options()
    {
        return $this->belongsToMany(\App\Option::class, 'option_user');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function opciones()
    {
        return $this->belongsToMany(\App\Option::class, 'option_user');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function uimages()
    {
        return $this->hasMany(\App\Models\Uimage::class);
    }

    public function imagen()
    {
        $imagen = $this->uimages()->first();

        $imagen = is_null($imagen) ? asset('img/avatar_none.png') : srcImgBynary($imagen);

        return $imagen;
    }

    public function isAdmin(){

        return $this->hasRole(Role::ADMIN);
    }

    public function isSuperAdmin()
    {
        return $this->hasRole(Role::SUPERADMIN);
    }

    public function isDev()
    {
        return $this->hasRole(Role::DEVELOPER);
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\UserDataTable;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\Role;
use App\Models\Uimage;
use App\User;
use App\Repositories\UserRepository;
use DB;
use Facades\App\Menu;
use App\Option;
use Flash;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Response;

class UserController extends AppBaseController
{
    /** @var  UserRepository */
    private $userRepository;

    public function __construct(UserRepository $userRepo)
    {
        $this->middleware('auth');
        $this->userRepository = $userRepo;
    }

    /**
     * Display a listing of the User.
     *
     * @param UserDataTable $userDataTable
     * @return Response
     */
    public function index(UserDataTable $userDataTable)
    {
        return $userDataTable->render('users.index');
    }

    /**
     * Show the form for creating a new User.
     *
     * @return Response
     */
    public function create()
    {
        $rols = Role::all();
        $rolsUser= [];
        $create =1;
        return view('users.create',compact('rols','rolsUser','create'));
    }

    /**
     * Store a newly created User in storage.
     *
     * @param CreateUserRequest $request
     *
     * @return Response
     */
    public function store(CreateUserRequest $request)
    {   

        $input = $request->all();
        $input['password'] = bcrypt($input['password']);


        try {
            DB::beginTransaction();

            $user = $this->userRepository->create($input);

            if($user && $request->rols){
                $user->syncRoles($request->rols);
            }

            if($user && $request->permisos){
                $user->syncRoles($request->permisos);
            }


            if ($user && $request->imagen){
                $this->saveImage($user,$request);
            }

        } catch (\Exception $exception) {
            DB::rollBack();
            $msg = $exception->getMessage();

            flash('Error: '.$msg)->error()->important();
            return redirect()->back();
        }


        DB::commit();


        Flash::success('User guardado exitosamente.');

        return redirect(route('users.index'));
    }

    /**
     * Display the specified User.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $user = $this->userRepository->findWithoutFail($id);

        if (empty($user)) {
            Flash::error('User no encontrado');

            return redirect(route('users.index'));
        }

        return view('users.show')->with('user', $user);
    }

    /**
     * Show the form for editing the specified User.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $userEdit = $this->userRepository->findWithoutFail($id);

        if (empty($userEdit)) {
            Flash::error('User no encontrado');

            return redirect(route('users.index'));
        }


        return view('users.edit',compact('userEdit'));
    }

    /**
     * Update the specified User in storage.
     *
     * @param  int              $id
     * @param UpdateUserRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateUserRequest $request)
    {
        $user = $this->userRepository->findWithoutFail($id);

        if (empty($user)) {
            Flash::error('User no encontrado');

            return redirect(route('users.index'));
        }

//        dd($user->toArray(),$request->toArray());
//
        $user->name = $request->name;
        $user->username = $request->username;
        $user->email = $request->email;


        if(!is_null($request->password) && !is_null($request->password_confirmation)){
            $user->password = bcrypt($request->password);
        }

        try {
            DB::beginTransaction();

            $user->save();

            $rols = $request->rols ? $request->rols : [];
            $user->syncRoles($rols);

            $permisos = $request->permisos ? $request->permisos : [];
            $user->syncPermissions($permisos);

            if ($user && $request->imagen){
                $this->saveImage($user,$request);
            }

        } catch (\Exception $exception) {
            DB::rollBack();
            $msg = $exception->getMessage();

            flash('Error: '.$msg)->error()->important();
            return redirect()->back();
        }


        DB::commit();

        Flash::success('User actualizado exitosamente.');

        return redirect(route('users.index'));
    }

    /**
     * Remove the specified User from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $user = $this->userRepository->findWithoutFail($id);

        if (empty($user)) {
            Flash::error('User no encontrado');

            return redirect(route('users.index'));
        }

        $this->userRepository->delete($id);

        Flash::success('User eliminado exitosamente.');

        return redirect(route('users.index'));
    }

    /**
     * Muestra al vista para poder asignar opciones del menu a un usuario
     *
     * @param $id id del usuario
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function menu(User $user){

        $opciones= Option::all();
        $menu= Menu::renderUser($opciones,0,$user);

        return view("users.menu",compact('user','menu'));
    }

    /**
     * Guarda lsa opciones de menu que se decidieron asignar al usuario
     *
     * @param Request $request
     * @param $id usuario
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function menuStore(User $user,Request $request){
        $opciones = [];
        // dd($user->id);// -> 2 
        //dd($request->all());
       //where('active', 1)  
       dd($request->all());
       $idx = $request->opciones[0];
        
       dd($idx); //ok
       
       $opcionesx = Option::select('ruta')->where('id', '=', $idx)->get();
        dd($opcionesx);


        print_r($datos);
        
        $id = $user->id;
        // dd($request->opciones);
        $opciones = [];

        // ******
        //$permisos = explode(',', $request->input('permisos')); 	
		// $ruta =  ;
        
        //         $permisos = explode(',', $ruta);
        
        //         foreach ($permisos as $permiso) {
        //             $permiso = trim($permiso);
        
        //             UsuarioPermisos::create([
        //                 'usuario_id' => $id,
        //                 'ruta' => trim($permiso),
        //             ]);
        //         }

        // ***** ciclo for contar las vueltas y con los id del permiso sacar las ruta y asignar y ya 
        
        foreach ($request->opciones as $id => $recursos){


            if (is_array($recursos)){

                $opciones[$id] = ['resources' => implode(',',$recursos)];
            }else{
                $opciones[$id] = $id ;
            }

        } 

        // dd($recursos);   

        $user->opciones()->sync(array_values($opciones));

        Flash::success('Menu del usuario actualizado!')->important();

        return redirect(route('users.index'));
    }

    public function saveImage(User $user,Request $request)
    {
        $file = $request->file('imagen');

        $imagen = New Uimage([
            'user_id' => $user->id,
            'data' => fileToBinary($file),
//            'data' => null,
            'name' => $file->getClientOriginalName(),
            'type' => $file->getMimeType(),
            'size' => $file->getSize(),
            'extension' => $file->extension()
        ]);

        $user->uimages()->delete();
        $user->uimages()->save($imagen);
    }

    /**
     * Muestra form para editar el perfil de usuario
     *
     * @param  int $id
     *
     * @return Response
     */
    public function editProfile($id)
    {
        $user = $this->userRepository->findWithoutFail($id);

        if (empty($user)) {
            Flash::error('User no encontrado');

            return redirect(route('users.index'));
        }

        return view('users.edit_profile',compact('user'));
    }

    /**
     * Update the specified User in storage.
     *
     * @param  int              $id
     * @param UpdateUserRequest $request
     *
     * @return Response
     */
    public function updateProfile(User $user, UpdateUserRequest $request)
    {

        if (empty($user)) {
            Flash::error('User no encontrado');

            return redirect()->back();
        }
 
        $user->name = $request->name;
        $user->email = $request->email;

        if(!is_null($request->password) && !is_null($request->password_confirmation)){
            $user->password = bcrypt($request->password);
        }

        $user->save();

        if ($user && $request->imagen){
            $this->saveImage($user,$request);
        }

        Flash::success('Perfil actualizado exitosamente.');

        return redirect()->back()->with('user',$user);
    }


    public function adminOauthClient()
    {
        return view('admin.admin_oauth_client');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('htmlheader_title')
	Crear User
@endsection

@include('layouts.plugins.select2')
@include('layouts.plugins.bootstrap_fileinput')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <h1 class="m-0 text-dark">
                        Crear User
                    </h1>
                </div><!-- /.col -->
                <div class="col ">
                    <a class="btn btn-outline-info float-right"
                       href="{{route('users.index')}}">
                        <i class="fa fa-list" aria-hidden="true"></i>&nbsp;<span class="d-none d-sm-inline">Listado</span>
                    </a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            @include('flash::message')
            @include('adminlte-templates::common.errors')

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            {!! Form::open(['route' => 'users.store','enctype' => "multipart/form-data"]) !!}
                                <div class="form-row">

                                    @include('users.fields')
                                    <!-- Submit Field -->
                                    <div class="form-group col-sm-12">
                                        <button type="submit" onClick="this.form.submit(); this.disabled=true;" class="btn btn-outline-success">Guardar</button>
                                        <a href="{!! route('users.index') !!}" class="btn btn-outline-default">Cancelar</a>
                                    </div>
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->

    @include('permissions.modal_form')
    @include('rols.modal_form_create')


@endsection

resources/views/users/datatables_actions.blade.php
<a href="{{ route('users.show', $id) }}" class='btn btn-default btn-xs' data-toggle="tooltip" title="Ver">
    <i class="fa fa-eye"></i>
</a>

<a href="{{ route('users.edit', $id) }}" class='btn btn-info btn-xs' data-toggle="tooltip" title="Editar">
    <i class="fa fa-edit"></i>
</a>

<a href="{{ route('user.menu',$id) }}" class="btn btn-sm btn-default">
    <span class="fa fa-list-alt" data-toggle="tooltip" title="Menu"></span>
</a>

<a href="#" onclick="deleteThis(this)" data-id="{{$id}}" data-toggle="tooltip" title="Eliminar" class='btn btn-danger btn-xs'>
    <i class="fa fa-trash-alt"></i>
</a>
<form action="{{ route('users.destroy', $id)}}" method="POST" id="delete-form{{$id}}">
    @method('DELETE')
    @csrf
</form>

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('htmlheader_title')
	Editar User
@endsection

@include('layouts.plugins.select2')
@include('layouts.plugins.bootstrap_fileinput')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <h1 class="m-0 text-dark">
                        Editar User
                    </h1>
                </div><!-- /.col -->
                <div class="col">
                    <a class="btn btn-outline-info float-right"
                       href="{{route('users.index')}}">
                        <i class="fa fa-list" aria-hidden="true"></i>&nbsp;<span class="d-none d-sm-inline">Listado</span>
                    </a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            @include('flash::message')
            @include('adminlte-templates::common.errors')

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                            {!! Form::model($userEdit, ['route' => ['users.update', $userEdit->id], 'method' => 'patch','enctype' => "multipart/form-data"]) !!}
                                <div class="form-row">

                                    @include('users.fields')
                                    <!-- Submit Field -->
                                    <div class="form-group col-sm-12">
                                        <button type="submit" onClick="this.form.submit(); this.disabled=true;" class="btn btn-outline-success">Guardar</button>
                                        <a href="{!! route('users.index') !!}" class="btn btn-outline-default">Cancelar</a>
                                    </div>
                                </div>
                           {!! Form::close() !!}

                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->

    @include('permissions.modal_form')
    @include('rols.modal_form_create')

@endsection

resources/views/users/edit_profile.blade.php
@extends('layouts.app')
@include('layouts.plugins.select2')
@include('layouts.plugins.bootstrap_fileinput')

@section('htmlheader_title')
	Editar perfil
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Editar perfil</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            @include('flash::message')
            @include('adminlte-templates::common.errors')

            {!! Form::model($user, ['route' => ['user.update.profile', $user->id], 'method' => 'patch','enctype' => "multipart/form-data"]) !!}
            <div class="row">
                <div class="col-lg-5">
                    <div class="card" >
                        <img class="card-img-top" src="{{Auth::user()->imagen()}}" alt="Card image cap" id="img-user">
                        <div class="card-body" style="padding: 0px">
                            <!-- Imagen Field -->

                            <div class="form-row " id="field-img" style="display: none">
                                <div class="form-group col-sm-12">
                                <input id="files" name="imagen" type="file">
                                </div>
                            </div>
                            <a class="btn btn-outline-info btn-sm btn-block" id="etidarImagen">Editar</a>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>

                <div class="col-lg-7">
                    <div class="card">
                        <div class="card-body">

                            <div class="form-row">
                                <!-- Name Field -->
                                <div class="form-group col-sm-6">
                                    {!! Form::label('name', 'Name:') !!}
                                    {!! Form::text('name', null, ['class' => 'form-control']) !!}
                                </div>

                                <!-- Email Field -->
                                <div class="form-group col-sm-6">
                                    {!! Form::label('email', 'Email:') !!}
                                    {!! Form::email('email', null, ['class' => 'form-control']) !!}
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="card card-default collapsed-card">
                        <div class="card-header">
                            <h3 class="card-title">Editar contraseña</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-edit"></i>
                                </button>
                            </div>
                            <!-- /.card-tools -->
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div class="form-row">
                            <!-- Password Field -->
                            <div class="form-group col-sm-6">
                                {!! Form::label('password', 'password:') !!}
                                {!! Form::password('password', ['class' => 'form-control']) !!}
                            </div>

                            <!-- Password Field -->
                            <div class="form-group col-sm-6">
                                {!! Form::label('password_confirmation', 'Confirmar password:') !!}
                                {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
                            </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->

            <div class="row">
                <!-- Submit Field -->
                <div class="form-group col-sm-12">
                    <button type="submit" onClick="this.form.submit(); this.disabled=true;" class="btn btn-outline-success">Guardar</button>
                    <a href="{{URL::previous()}}" class="btn btn-default">Cancelar</a>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection
@push('scripts')
<script>
    $(function () {
        $("#etidarImagen").click(function () {
           console.log('editar imagen');
            $('#field-img').show();
            $('#img-user').hide();

        });

        var $input = $("#files");
        $input.fileinput({
            {{--uploadUrl: "{{route('api.temp_files.multi_store',Auth::user()->id)}}", // server upload action--}}
            //            uploadAsync: false,
            showUpload: false, // hide upload button
            showRemove: false, // hide remove button
//            minFileCount: 1,
//            maxFileCount: 5,
            allowedFileExtensions: ["png","bmp","gif","jpg","pdf"],
        });
    })
</script>
@endpush

resources/views/users/fields.blade.php
<!-- Username Field -->
<div class="form-group col-sm-3">
    {!! Form::label('username', 'Username:') !!}
    {!! Form::text('username', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-3">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field --> 
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Rols Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rols', 'Roles:') !!}

    @can('Crear Rol')
        <a class="success" data-toggle="modal" href="#modal-form-roles" tabindex="1000">nuevo</a>
    @endcan
    {!!
        Form::select(
            'rols[]',
            slc(\App\Models\Role::class,'name','name',null),
            isset($userEdit) ? $userEdit->getRoleNames() : null,
            ['id'=>'rols','class' => 'form-control', 'multiple' => 'multiple','style'=>'width: 100%']
        )
    !!}
</div>

<!-- Permisos Field -->
<div class="form-group col-sm-6">
    {!! Form::label('permisos', 'Permisos Directos:') !!}

    @can('crear permiso')
        <a class="success" data-toggle="modal" href="#modal-form-permissions" tabindex="1000">nuevo</a>
    @endcan

    {!!
        Form::select(
            'permisos[]',
            slc(\App\Models\Permission::class,'name','name',null),
            isset($userEdit) ? $userEdit->getDirectPermissions()->pluck('name','name') : null,
            ['id'=>'permisos','class' => 'form-control', 'multiple' => 'multiple','style'=>'width: 100%']
        )
    !!}
</div>

<div class="form-group col-sm-12" style="padding: 0px; margin: 0px">
</div>
@if(!isset($create))
    <div class="form-group col-sm-12">
        <a class="" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            <span class=" btn btn-outline-primary">Editar también contraseña</span>
        </a>
    </div>
@endif


<div class="col-sm-12 {{ !isset($create) ? "collapse" : '' }}" id="collapseExample">
    <div class="form-row">

    <!-- Password Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('password', 'password:') !!}
        {!! Form::password('password', ['class' => 'form-control']) !!}
    </div>

    <!-- Password Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('password_confirmation', 'Confirmar password:') !!}
        {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
    </div>
    </div>
</div>

@if(!isset($create))
<!-- Imagen Field -->
<div class="form-group col-sm-4">
    <div class="card" >
        <img class="card-img-top" src="{{$userEdit->imagen()}}" alt="Card image cap" id="img-user">
        <div class="card-body" style="padding: 0px">
            <!-- Imagen Field -->

            <div class="form-row " id="field-img" style="display: none">
                <div class="form-group col-sm-12">
                    <input id="files" name="imagen" type="file">
                </div>
            </div>
            <a  href="#" class="btn btn-outline-info btn-sm btn-block" id="etidarImagen">Editar</a>
        </div>
    </div>
</div>
@else
    <!-- Imagen Field -->
    <div class="form-group col-sm-4">
        <input id="files" name="imagen" type="file">
    </div>
@endif

@push('scripts')
<script>
    $(function () {
        $("#etidarImagen").click(function (e) {
            e.preventDefault();
            console.log('editar imagen');
            $('#field-img').show();
            $('#img-user').hide();

        });
        $("#rols,#permisos").select2();

        var $input = $("#files");
        $input.fileinput({
            {{--uploadUrl: "{{route('api.temp_files.multi_store',Auth::user()->id)}}", // server upload action--}}
//            uploadAsync: false,
            showUpload: false, // hide upload button
            showRemove: false, // hide remove button
//            minFileCount: 1,
//            maxFileCount: 5,
            allowedFileExtensions: ["png","bmp","gif","jpg","pdf"],
        });
    })
</script>
@endpush