routes/web.php
<?php

Route::get('pruebas', function () {
 
});
// vista comun
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'DashboardController@index');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::resource('pregunta', 'PreguntaController')->except([
    'destroy'
]);

Route::get('preguntas/{id}', 'PreguntaController@eliminar')->name('preguntas.eliminar');

// Route::delete('/preguntas/{id}', 'PreguntaController@eliminar')
//     ->where('id', '[0-9]+')
//     ->name('preguntas.eliminar');


Route::get('user/profile/{user}', 'UserController@editProfile')->name('user.edit.profile');;
Route::patch('user/profile/{user}', 'UserController@updateProfile')->name('user.update.profile');;

Route::resource('configurations', 'ConfigurationController');
Route::resource('rols', 'RolController');
Route::resource('users', 'UserController');

Route::get('user/{user}/menu', 'UserController@menu')->name('user.menu');;
Route::patch('user/menu/{user}', 'UserController@menuStore')->name('users.menuStore');


Route::get('option/create/{padre}', 'OptionMenuController@create')->name('option.create');
Route::get('option/orden', 'OptionMenuController@updateOrden')->name('option.order');
Route::get('option/orden', 'OptionMenuController@updateOrden')->name('option.order.store');
Route::resource('options',"OptionMenuController");

Route::get('oauth/client',"UserController@adminOauthClient")->name('oauth.clients');


Route::get('prueba/pdf', function (\App\Extensiones\Fpdf $fpdf) {
    $fpdf->AddPage();
    $fpdf->SetFont('Courier', 'B', 18);
    $fpdf->Cell(50, 25, 'Hello World!');
    $fpdf->Output();
    exit();
})->name('prueba.pdf');

Route::resource('permissions', 'PermissionController');

Route::get('/consulta/respuesta',        'ConsultaController@index')->name('consulta.index');
Route::get('/consulta/respuesta/{id}', 'ConsultaController@stor')->name('consulta.stor');
Route::post('/consulta/respuestas/{id}',  'ConsultaController@store')->name('consultas.store');

Route::get('/consulta/respondidas',     'ConsultaController@edit')->name('consulta.edit');
Route::get('/consulta/cerradas',        'ConsultaController@show')->name('consulta.show');

//consulta/respuesta/{$id}
 

/*

Route::get('/customers', 'CustomerController@index')
->name('customerIndex');
Route::get('/customers/create', 'CustomerController@create')
->name('customerCreate');
Route::post('/customers', 'CustomerController@store')
->name('customerStore');
Route::get('/customers/{customer}', 'CustomerController@show')
->name('customerShow');
Route::get('/customers/{customer}/edit', 'CustomerController@edit')
->name('customerEdit');
Route::put('/customers/{customer}', 'CustomerController@update')
->name('customerUpdate');
Route::delete('/customers/{customer}', 'CustomerController@destroy')
->name('customerDestroy');
*/

app/Menu.php
<?php
/**
 * Created by PhpStorm.
 * User: Usuario
 * Date: 9/03/2017
 * Time: 4:22 PM
 */

namespace App;


class Menu{

    /**
     * Comprueba si una opcion tien sub opciones
     * @param $opciones
     * @param $id
     * @return bool
     */
    public function has_children($opciones,$id) {
        foreach ($opciones as $op) {
            if ($op->padre == $id)
                return true;
        }
        return false;
    }

    /**
     * Nuevo menu que se muestra en la seccion sidebar
     * @param $opciones
     * @param int $parent
     * @return string
     */
    public function render($opciones,$parent=0){

        $result = $parent==0 ? "<ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"true\">" : "<ul class=\"nav nav-treeview\">";

        foreach ($opciones as $op)
        {
            if ($op->padre == $parent){

                try{
                    $rout =route($op->ruta.'');
                }catch (\Exception $e){
                    $rout = '';
                };

                $has_children= ($this->has_children($opciones,$op->id) || $op->padre=="") ? true : false;

                $result.= $has_children ? "<li class=\"nav-item has-treeview\">" : "<li class=\"nav-item\">";
                $result.= $op->nombre=='separador' ? "" : "<a href=\"{$rout}\" class=\"nav-link\">";
                $result.= $op->nombre=='separador' ? "" : "<i class=\"fa {$op->icono_l} nav-icon\"></i>";
                $result.= "<p>";
                $result.= $op->nombre=='separador' ? '':  $op->nombre ;
                if ($op->icono_r){
                    $result.= $has_children ? "<i class=\"right  fa {$op->icono_r}\"></i>" : "";
                }
                $result.= "</p>";
                $result.= "</a>";

                if ($this->has_children($opciones,$op->id))
                    $result.= $this->render($opciones,$op->id);
                $result.= "</li>";
            }
        }
        $result.= "</ul>";

        return $result;
    }


    /**
     * Genera el menu con opciones para crear, editar y eliminar las opciones
     * @param $opciones
     * @param int $parent
     * @return string
     */
    public function renderAdmin($opciones,$parent=0){

        $result = "<ul class=\"sortable list-group\">";

        foreach ($opciones as $op) {
            if ($op->padre == $parent){

                $actionEdit = action('OptionMenuController@edit',$op->id);
                $actionDelet = action('OptionMenuController@destroy',["id" => $op->id]);
//                $rutaNew= url("/admin/option/create/{$op->id}");
                $rutaNew= route('option.create',$op->id);

                $result.= "<li class='list-group-item' id='{$op->id}' ><span class='fa fa-arrows-alt'></span>&nbsp;&nbsp;<b>{$op->nombre}</b>";
                $result.= " &nbsp;<a href=\"{$rutaNew}\" class='text-success text-sm' data-toggle=\"tooltip\" title=\"Nueva opcion\"><span class=\"fa fa-plus\"></span></a>";
                $result.= " &nbsp;<a href=\"{$actionEdit}\" data-toggle=\"tooltip\" title=\"Editar\"><span class='fa fa-edit'></span></a>";
                $result.= " &nbsp;<a data-toggle='modal' href='#modal-delete' data-action=\"{$actionDelet}\" class='text-danger btn-delete' ><span class=\"fa fa-trash-alt\"  data-toggle=\"tooltip\" title=\"Eliminar\"></span></a>";

                if ($this->has_children($opciones,$op->id))
                    $result.=  $this->renderAdmin($opciones,$op->id);
                $result.= "</li>";
            }
        }
        $result.= "</ul>";


        return $result;
    }

    /**
     * Genera el menu con checkbos en cada opción para asignar o quitar opciones al usuario
     * @param $opciones
     * @param int $parent
     * @param $usuario
     * @return string
     */
    public function renderUser($opciones,$parent=0,$usuario){

        $opcionesUsuario =  array_pluck($usuario->opciones->toArray(),'id');

        $result = "<ul>";

        foreach ($opciones as $op) {
            if ($op->padre == $parent){

                $checked = in_array($op->id,$opcionesUsuario) ? 'checked' : '';

                $tienHijos = $this->has_children($opciones,$op->id) ? 1 : 0;
                $tienPadre = $op->padre ? 1 : 0;

                $result.= "<li>";
                $result.= "<div class=\"checkbox\">
                                	<label>
                                		<input type=\"checkbox\" value=\"{$op->id}\" name=\"opciones[]\"  data-tiene-hijos='$tienHijos' data-tiene-padre='$tienPadre' $checked >
                                		{$op->nombre}
                                	</label>
                                </div>";

                if ($this->has_children($opciones,$op->id))
                    $result.= $this->renderUser($opciones,$op->id,$usuario);
                $result.= "</li>";
            }
        }
        $result.= "</ul>";


        return $result;
    }

}

resources/views/admin/menu/create.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Nueva opción del menu</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="content">
        <div class="container-fluid">

            @include('adminlte-templates::common.errors')

            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-warning">
                        <!-- /.card-header -->
                        <div class="card-body">
                            {!! Form::open(['route' => 'options.store']) !!}
                                @include("admin.menu.fields")

                                <!-- Submit Field -->
                                <div class="form-group col-sm-12">
                                    <button type="submit" onClick="this.form.submit(); this.disabled=true;" class="btn btn-outline-success">Guardar</button>
                                    <a href="{!! route('options.index') !!}" class="btn btn-outline-default">Cancelar</a>
                                </div>
                            {!! Form::close() !!}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>

@endsection

resources/views/admin/menu/edit.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Editar opción: {{$opcion->nombre}}</h1>
                </div><!-- /.col -->

                <div class="col">
                    <a class="btn btn-outline-info float-right"
                       href="{{route('options.index')}}">
                        <i class="fa fa-list" aria-hidden="true"></i>&nbsp;<span class="d-none d-sm-inline">Listado</span>
                    </a>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="content">
        <div class="container-fluid">

            @include('flash::message')

            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-warning">
                        <!-- /.card-header -->
                        <div class="card-body">
                            {!! Form::model($opcion, ['route' => ['options.update', $opcion->id], 'method' => 'patch']) !!}
                                @include('admin.menu.fields')

                                <!-- Submit Field -->
                                <div class="form-group col-sm-12">
                                    <button type="submit" onClick="this.form.submit(); this.disabled=true;" class="btn btn-outline-success">Guardar</button>
                                    <a href="{!! route('options.index') !!}" class="btn btn-outline-default">Cancelar</a>
                                </div>
                            {!! Form::close() !!}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>

@endsection

resources/views/admin/menu/fields.blade.php
<div class="form-group">
    <label for="padre" class="col-sm-2 control-label">Opción superior</label>
    <div class="col-sm-6">
        {{$padre->nombre ?? "Ninguna"}}

        <input type="hidden" name="padre" value="{{$padre->id ?? ""}}">

    </div>
</div>

<div class="form-group col-sm-6">
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
</div>


<div class="form-group col-sm-6">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    {!! Form::text('descripcion', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('ruta', 'Ruta:') !!}
    {!! Form::text('ruta', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    <label for="icono_l" class="col-sm-2 control-label">Icono izquierdo</label>
    <div class="col-sm-10">
        {!! Form::text('icono_l', null, ['class' => 'form-control input-icon']) !!}
        @foreach($iconos as $icono)
            <label class="radio-inline">
                @isset($opcion)
                    <input type="radio" name="x" id="inputID" value="{{$icono}}" class="radio-iconos" {{$icono==$opcion->icono_l ? "checked" : ''}}>
                @else
                    <input type="radio" name="x" id="inputID" value="{{$icono}}" class="radio-iconos">
                @endisset
                <i class="fa {{$icono}}"></i>
            </label>
        @endforeach

    </div>
</div>

<div class="form-group">
    <label for="icono_r" class="col-sm-2 control-label">Icono derecho</label>
    <div class="col-sm-10">
        {!! Form::text('icono_r', null, ['class' => 'form-control input-icon']) !!}
        <label class="radio-inline">
            <input type="radio" name="y" id="inputID" value="" checked>
            ninguno
        </label>
        @foreach($iconos as $icono)
            <label class="radio-inline">
                @isset($opcion)
                    <input type="radio" name="y" id="inputID" value="{{$icono}}" class="radio-iconos" {{$icono==$opcion->icono_r ? "checked" : ''}}>
                @else
                    <input type="radio" name="y" id="inputID" value="{{$icono}}" class="radio-iconos" >
                @endisset
                <i class="fa {{$icono}}"></i>
            </label>
        @endforeach
    </div>
</div>
@push('scripts')
<script>
    $(function () {
        $(".radio-iconos").click(function (e) {
//            e.preventDefault();
            var opcion = $(this).val();
            var input = $(this).parent().parent().find('.input-icon');
            console.log('Cambio icono',opcion,input);

            input.val(opcion)
        });
    })
</script>
@endpush

resources/views/admin/menu/form.blade.php
<form class="form-horizontal" role="form" method="POST" action="{{ action('OptionMenuController@store') }}">
        {{ csrf_field() }}
        
        <div class="form-group {{ $errors->has('padre') ? ' has-error ': '' }}">
        	<label for="padre" class="col-sm-2 control-label">Opción superior</label>
        	<div class="col-sm-6">
        		{{--<select name="padre" id="padre" class="form-control"  autofocus>--}}
                    {{--<option value=""> -- Seleccione Uno -- </option>--}}
                    {{--@foreach($ops as $op)--}}
                        {{--<option value="{{$op->id}}" {{ $op->id==$padre->id ? 'selected' : '' }}> {{$op->nombre}}</option>--}}
                    {{--@endforeach--}}
                {{--</select>--}}
                {{$padre->nombre ?? "Ninguna"}}

                <input type="hidden" name="padre" value="{{$padre->id ?? ""}}">

            </div>
        </div>

        <div class="form-group {{ $errors->has('nombre') ? ' has-error ': '' }}">
            <label for="nombre" class="col-sm-2 control-label">Nombre</label>
            <div class="col-sm-6">
                <input type="text" name="nombre" class="form-control" id="nombre" placeholder="Nombre" value="{{old('nombre')}}">
            </div>
        </div>

        <div class="form-group {{ $errors->has('descripcion') ? ' has-error ': '' }}">
            <label for="descripcion" class="col-sm-2 control-label">Descripcion</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" name="descripcion" id="descripcion" placeholder="Descripcion" value="{{old('descripcion')}}">
            </div>
        </div>

        <div class="form-group {{ $errors->has('ruta') ? ' has-error ': '' }}">
            <label for="ruta" class="col-sm-2 control-label">Ruta</label>
            <div class="col-sm-6">
                <input name="ruta" type="text" class="form-control" id="ruta" placeholder="Ruta" value="{{ old('ruta') }}">
            </div>
        </div>

        <div class="form-group {{ $errors->has('icono_l') ? ' has-error ': '' }}">
            <label for="icono_l" class="col-sm-2 control-label">Icono izquierdo</label>
            <div class="col-sm-10">

                @foreach($iconos as $icono)
                    <label class="radio-inline">
                        <input type="radio" name="icono_l" id="inputID" value="{{$icono}}" {{$icono=="fa-circle-o" ? "checked" : ''}}>
                        <i class="fa {{$icono}}"></i>
                    </label>
                @endforeach

            </div>
        </div>

        <div class="form-group {{ $errors->has('icono_r') ? ' has-error ': '' }}">
            <label for="icono_r" class="col-sm-2 control-label">Icono derecho</label>
            <div class="col-sm-10">
                <label class="radio-inline">
                    <input type="radio" name="icono_r" id="inputID" value="" checked>
                    ninguno
                </label>
                @foreach($iconos as $icono)
                    <label class="radio-inline">
                        <input type="radio" name="icono_r" id="inputID" value="{{$icono}}" >
                        <i class="fa {{$icono}}"></i>
                    </label>
                @endforeach
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-6 col-md-offset-2">
                <button type="submit" class="btn btn-primary">
                    Guardar
                </button>

                <a href="{{ URL::previous() }}">
                    <button type="button" class="btn btn-danger">
                        Cancelar
                    </button>
                </a>
            </div>
        </div>
    </form>

resources/views/admin/menu/index.blade.php
@extends("layouts.app")

@push('css')
<style>
	.sortable li {
		list-style-type: none;
	}
</style>
@endpush
@include('layouts.plugins.jquery-ui')

@section("content")

	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Administración de opciones del menu</h1>
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<div class="content">
		<div class="container-fluid">
			@include('flash::message')
			<div class="row">
				<div class="col-lg-12">
					<div class="card card-warning">
						<!-- /.card-header -->
						<div class="card-body">
							<!--Contenido-->
							{!! $menu !!}

							<ul>
								<li>
									<a href="{{route('option.create',0)}}"
									   class='text-success text-sm' data-toggle="tooltip" title="Nueva opcion">
										<span class="fa fa-plus"></span>
									</a>
								</li>
							</ul>

							<!--Fin Contenido-->
						</div>
						<!-- /.card-body -->
					</div>
				</div>
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</div>



	<div class="modal fade" id="modal-delete">
		<form action="" method="post" role="form" id="form-delete" >
			{{ csrf_field() }}
			{{method_field('DELETE')}}
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Eliminar opcion</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">
						Seguro que desea eliminar?
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">No</button>
						<button type="submit" class="btn btn-primary">Si</button>
					</div>
				</div><!-- /.modal-content -->
			</div><!-- /.modal-dialog -->
		</form>
	</div><!-- /.modal -->

@stop
@push("scripts")
    <script src="{{asset("js/axios.min.js")}}"></script>
	<script>
		$(function(){

            $.widget.bridge('uibutton', $.ui.button);

			$(".btn-delete").click(function () {
				$("#form-delete").attr("action",$(this).data("action"))
			});

			$( ".sortable" ).sortable({
				update: function( event, ui ) {

					var  opciones=[];
					$(this).find('li').each(function (index,elemet) {
						opciones.push($(this).attr('id'));
					});

					var url = "{{route("option.order.store")}}";
					var params= { params: {opciones: opciones} };

					consolaJs(opciones,url);

					axios.get(url,params).then(response => {
						consolaJs(response.data);
						toastr.success(response.data.message);
					})
					.catch(error => {
						consolaJs(error);
					    toastr.error(error.response.message);
					});

				}
			}).disableSelection();
		});
	</script>
@endpush