routes/web.php
<?php

Route::get('pruebas', function () {
 
});
// vista comun
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'DashboardController@index');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::resource('pregunta', 'PreguntaController')->except([
    'destroy'
]);

Route::get('preguntas/{id}', 'PreguntaController@eliminar')->name('preguntas.eliminar');

// Route::delete('/preguntas/{id}', 'PreguntaController@eliminar')
//     ->where('id', '[0-9]+')
//     ->name('preguntas.eliminar');


Route::get('user/profile/{user}', 'UserController@editProfile')->name('user.edit.profile');;
Route::patch('user/profile/{user}', 'UserController@updateProfile')->name('user.update.profile');;

Route::resource('configurations', 'ConfigurationController');
Route::resource('rols', 'RolController');
Route::resource('users', 'UserController');

Route::get('user/{user}/menu', 'UserController@menu')->name('user.menu');;
Route::patch('user/menu/{user}', 'UserController@menuStore')->name('users.menuStore');


Route::get('option/create/{padre}', 'OptionMenuController@create')->name('option.create');
Route::get('option/orden', 'OptionMenuController@updateOrden')->name('option.order');
Route::get('option/orden', 'OptionMenuController@updateOrden')->name('option.order.store');
Route::resource('options',"OptionMenuController");

Route::get('oauth/client',"UserController@adminOauthClient")->name('oauth.clients');


Route::get('prueba/pdf', function (\App\Extensiones\Fpdf $fpdf) {
    $fpdf->AddPage();
    $fpdf->SetFont('Courier', 'B', 18);
    $fpdf->Cell(50, 25, 'Hello World!');
    $fpdf->Output();
    exit();
})->name('prueba.pdf');

Route::resource('permissions', 'PermissionController');

Route::get('/consulta/respuesta',        'ConsultaController@index')->name('consulta.index');
Route::get('/consulta/respuesta/{id}', 'ConsultaController@stor')->name('consulta.stor');
Route::post('/consulta/respuestas/{id}',  'ConsultaController@store')->name('consultas.store');

Route::get('/consulta/respondidas',     'ConsultaController@edit')->name('consulta.edit');
Route::get('/consulta/cerradas',        'ConsultaController@show')->name('consulta.show');

//consulta/respuesta/{$id}
 

/*

Route::get('/customers', 'CustomerController@index')
->name('customerIndex');
Route::get('/customers/create', 'CustomerController@create')
->name('customerCreate');
Route::post('/customers', 'CustomerController@store')
->name('customerStore');
Route::get('/customers/{customer}', 'CustomerController@show')
->name('customerShow');
Route::get('/customers/{customer}/edit', 'CustomerController@edit')
->name('customerEdit');
Route::put('/customers/{customer}', 'CustomerController@update')
->name('customerUpdate');
Route::delete('/customers/{customer}', 'CustomerController@destroy')
->name('customerDestroy');
*/

app/Http/Controllers/PreguntaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use App\DataTables\PreguntaDataTable;
use App\Repositories\PreguntasRepository;
use App\Notas;
use App\Respuesta;

use DB;
use Flash;
use App\User;
use Illuminate\Http\Request;
use Response;

class PreguntaController extends Controller
{
    private $preguntaRepository;
    //PreguntasRepository $preguntaRepo
    public function __construct()
    {
        $this->middleware('auth');
        //$this->preguntaRepository = $preguntaRepo;
    }

    /**
     * DashboardController constructor.
     */
    

    public function index(PreguntaDataTable $preguntaDataTable)
    {
        //$rols = Role::all();
        //$rolsUser= [];
        $pregunta =1;
       // dd( $pregunta);
       // return view('pregunta',compact('pregunta'));
       return $preguntaDataTable->render('pregunta.index');
    
        //return view('dashboard'); 
    }


    public function show( $id )
    {   
        //dd($id);
        $v = Respuesta::select('*')->where('id_notas', $id)->get()->count();  
        
        //dd($v);
        if (empty($v)) {
            Flash::error('Consulta no encontrado');

            return redirect(route('pregunta.index'));
        }
        
        
        $ve = [];
        $ve = Respuesta::select('*')->where('id_notas', $id)->get(); 
         $ver = Respuesta::select('*')->where('id_notas', $id)->get(); 
         $pregunta = ($ver[0]['pregunta']);
        
       


        $ver = [];
        foreach ($ve as $key => $n) {
            $ver[]= [
                'id' => $n->id,
               'respuesta' => $n->respuesta,
                'fecha' => $n->fecha,
                //'status' => $n->status,
            ];

             
           }

          // dd($ver);
           // c
        
        // id" => 1
        // "id_notas" => 18
        // "id_users" => 1
        // "pregunta" => "compra un usb"
        // "respuesta" => "si dale"
        // "fecha" => "11-05-2020"
        // "status" => 1
        // "created_at" => "2020-05-11 16:24:43"
        // "updated_at" => "2020-05-11 16:24:43"
        // "deleted_at" => null
        
        return view('pregunta.show',compact('ver', 'pregunta'));
        //return view('dashboard'); 
    }

    public function edit($id)
    {   
        //dd("aki estoy editar");
        //dd($id);
        $edit = Notas::find($id);
        //DB::table('notas')->select('*')->where('id', 1)->get()->toarray(); 
        //dd($edit->id);
        if (is_null($edit)) {
            Flash::error('Consulta no encontrado');

            return redirect(route('pregunta.index'));
        }


        return view('pregunta.editar',compact('edit'));
    }

    public function form()
    {
        //dd("aki");
        //$rols = Role::all();
        //$rolsUser= [];
        $pregunta =1;
        return view('pregunta',compact('pregunta'));
    
        //return view('dashboard'); 
    }

    public function create()
    {
        $rols = Notas::all();
        $rolsUser= [];
        $create =1;
        return view('pregunta.create',compact('rols','rolsUser','create'));
    }

    public function store (User $user, Request $request)
    {   
        DB::beginTransaction();
        $personas_id = Auth::user()->id;
       // dd($personas_id);
       // dd($request->all());
       // dd($request->descripcion);
        $request->validate([
            'pregunta'=>'required',
            'descripcion'=>'required',
            //'email'=>'required'
        ]);
        // 'id_user',
        // 'pregunta',
        // 'descripcion',
        // 'status'
       $num = 0;

      //  Notas::create($request->all());

      $nota = new Notas([
          'id_user'     => $personas_id,
          'pregunta'    => $request->pregunta,
          'descripcion' => $request->descripcion,
          'status'      => $num
      ]);
      $nota->save();

        //	$vehiculo = $id == 0 ? new Vehiculo() : Vehiculo::find($id);
        // $contact = new Contact([
        //     'first_name' => $request->get('first_name'),
        //     'last_name' => $request->get('last_name'),
        //     'email' => $request->get('email'),
        //     'job_title' => $request->get('job_title'),
        //     'city' => $request->get('city'),
        //     'country' => $request->get('country')
        // ]);
        // $contact->save();

        DB::commit();


        Flash::success('Pregunta guardado exitosamente.');

        return redirect(route('pregunta.index'));
        //return redirect('/dashboard')->with('success', 'Contact saved!');


        //return view('pregunta',compact('pregunta'));
        //return view('dashboard'); 
    }

    
    public function eliminar($id)
    {  
        // dd($id);
        $user = Notas::find($id);
            //dd( $user);
        if (is_null ($user)) {
            Flash::error('la consulta no se fue encontrado');

            return redirect(route('pregunta.index'));
        }

        $user->delete();

        Flash::success('La consulta fue eliminada exitosamente.');

        return redirect(route('pregunta.index'));
    }

    public function update( Request $request , $id )
    {  // dd($id);
         // dd($request->all());
                 
           $request->validate([
               'pregunta'=>'required',
               'descripcion'=>'required',
               'status'=>'required'
           ]);
           
           //dd($request->all());
          // Notas::create($request->all());

          //Notas::select('*')->where('id', '=', $id)->get();
          //dd($flight);
         $flight = Notas::find($id);
         $flight->pregunta = $request->pregunta;
         $flight->descripcion = $request->descripcion;
         $flight->status = $request->status;
         $flight->save();

        // $flight = $id == 0 ? new Notas() : Notas::find($id);
        // $flight->fill($request->all());
        // $flight->save();

        if (is_null($flight)) {
            Flash::error('error de consulta');

            return redirect(route('pregunta.index'));
        }

    
        Flash::success('La consulta fue modificada exitosamente.');

        return redirect(route('pregunta.index'));
    }

    
}

// |          GET|HEAD  | pregunta                                | pregunta.index                    | App\Http\Controllers\DashboardController@index                            | web,auth                                     |
// |        | POST      | pregunta                                | pregunta.store                    | App\Http\Controllers\DashboardController@store                            | web,auth                                     |
// |        | GET|HEAD  | pregunta/create                         | pregunta.create                   | App\Http\Controllers\DashboardController@create                           | web,auth                                     |
// |        | DELETE    | pregunta/{preguntum}                    | pregunta.destroy                  | App\Http\Controllers\DashboardController@destroy                          | web,auth                                     |
// |        | GET|HEAD  | pregunta/{preguntum}                    | pregunta.show                     | App\Http\Controllers\DashboardController@show                             | web,auth                                     |
// |        | PUT|PATCH | pregunta/{preguntum}                    | pregunta.update                   | App\Http\Controllers\DashboardController@update                           | web,auth                                     |
// |        | GET|HEAD  | pregunta/{preguntum}/edit               | pregunta.edit                     | App\Http\Controllers\DashboardController@edit                             | web,auth                                     |
// |     

resources/views/pregunta/create.blade.php
@extends('layouts.app')

@section('htmlheader_title')
	Crear User
@endsection

@include('layouts.plugins.select2')
@include('layouts.plugins.bootstrap_fileinput')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <h1 class="m-0 text-dark">
                        Crear Nueva Consula
                    </h1>
                </div><!-- /.col -->
                <div class="col ">
                    <a class="btn btn-outline-info float-right"
                       href="{{route('pregunta.index')}}">
                        <i class="fa fa-list" aria-hidden="true"></i>&nbsp;<span class="d-none d-sm-inline">Listado</span>
                    </a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            @include('flash::message')
            @include('adminlte-templates::common.errors')

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            {!! Form::open(['route' => 'pregunta.store','enctype' => "multipart/form-data"]) !!}
                                <div class="form-row">

                                    @include('pregunta.fields')
                                    <!-- Submit Field -->
                                    <div class="form-group col-sm-12">
                                        <button type="submit" onClick="this.form.submit(); this.disabled=true;" class="btn btn-outline-success">Guardar</button>
                                        <a href="{!! route('users.index') !!}" class="btn btn-outline-default">Cancelar</a>
                                    </div>
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->

    @include('permissions.modal_form')
    @include('rols.modal_form_create')


@endsection

resources/views/pregunta/datatables_actions.blade.php
<a href="{{ route('pregunta.show', $id) }}" class='btn btn-default btn-xs' data-toggle="tooltip" title="Ver">
    <i class="fa fa-eye"></i>
</a>

<a href="{{ route('pregunta.edit', $id) }}" class='btn btn-info btn-xs' data-toggle="tooltip" title="Editar">
    <i class="fa fa-edit"></i>
</a>

<!--
-->
<a href="{{ route('preguntas.eliminar', $id) }}" class="btn btn-danger btn-xs">
    <span class="fa fa-trash-alt" data-toggle="tooltip" title="Eliminar{{$id}}"></span>
</a> 

resources/views/pregunta/editar.blade.php
@extends('layouts.app')

@section('htmlheader_title')
Crear User
@endsection

@include('layouts.plugins.select2')
@include('layouts.plugins.bootstrap_fileinput')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h1 class="m-0 text-dark">
                    Crear Nueva Consula
                </h1>
            </div><!-- /.col -->
            <div class="col ">
                <a class="btn btn-outline-info float-right" href="{{route('pregunta.index')}}">
                    <i class="fa fa-list" aria-hidden="true"></i>&nbsp;<span class="d-none d-sm-inline">Listado</span>
                </a>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        @include('flash::message')
        @include('adminlte-templates::common.errors')

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        {!! Form::model($edit, ['route' => ['pregunta.update', $edit->id], 'method' => 'patch']) !!}
                        <div class="form-row">

                            @include('pregunta.fields')
                            <!-- Submit Field -->
                            <div class="form-group col-sm-12">
                                <button type="submit" class="btn btn-outline-success">Guardar</button>
                                <a href="{!! route('rols.index') !!}" class="btn btn-outline-default">Cancelar</a>
                            </div>
                        </div>

                       {!! Form::close() !!}



                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content -->

@include('permissions.modal_form')
@include('rols.modal_form_create')


@endsection

resources/views/pregunta/fields.blade.php
<!-- Pregunta Field -->
<div class="form-group col-sm-10">
    {!! Form::label('pregunta', 'lap pregunta de la consulta:') !!}
    {!! Form::text('pregunta', null, ['class' => 'form-control']) !!}
</div>

<!-- descripcion Field -->
<div class="form-group col-sm-10">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    {!! Form::text('descripcion', null, ['class' => 'form-control']) !!}
</div>


<div class="form-group col-sm-12" style="padding: 0px; margin: 0px">
</div>

@if(!isset($create))
<div class="form-group col-sm-12">
    <a class="" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false"
        aria-controls="collapseExample">
        <span class=" btn btn-outline-primary">Editar también contraseña</span>
    </a>
</div>
@endif


<div class="col-sm-12 {{ isset($create) ? "collapse" : '' }}" id="collapseExample">
    <div class="form-row">

        <!-- Password Field -->
        <div class="form-group col-sm-6">
               
                
                        <label for="status"> status </label>
                        <select class="form-control" value="" name="status" id="status">
                          <option value="0"> abierto </option>
                          <option value="1"> cerrado </option>
                         
                        </select>
                      </div>
                
        </div>

        
    </div>
</div>

resources/views/pregunta/index.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection
@extends('layouts.app')

@section('htmlheader_title')
    Pregunta 
@endsection

@include('layouts.plugins.jquery-ui')

@push('css')
    <!-- Ionicons -->
    <!-- <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"> -->
    <!-- Theme style -->
    {{--<link rel="stylesheet" href="dist/css/adminlte.min.css">--}}
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{asset('plugins/morris/morris.css')}}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.css')}}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{asset('plugins/datepicker/datepicker3.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('plugins/daterangepicker/daterangepicker-bs3.css')}}">


    @endpush

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
                <div class="col">
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">
                                <a class="btn btn-outline-success"
                                    href="{!! route('pregunta.create') !!}">
                                    <i class="fa fa-plus"></i>
                                    <span class="d-none d-sm-inline">Agregar Nuevo</span>
                                </a>
                            </li>
                        </ol>
                    </div><!-- /.col -->
            <div class="row mb-2">
                <div class="col">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div>
                <!-- 
                    head de la pag
                 -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">        
                @include('flash::message')
                @include('adminlte-templates::common.errors')
            <div class="row">
                
                
                <div class="table-responsive">
                    {!! $dataTable->table(['width' => '100%']) !!}
                </div>
                
            </div>

        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@section('scripts')
@include('layouts.datatables_js')
{!! $dataTable->scripts() !!}
<script>
    $(function () {
            var dt = window.LaravelDataTables["dataTableBuilder"];
            
            //Cuando dibuja la tabla
            dt.on( 'draw.dt', function () {
                $(this).addClass('table-sm table-striped table-bordered table-hover');
                $('[data-toggle="tooltip"]').tooltip();
            });
            
        })
        </script>
@endsection
@push('scripts')
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <!-- <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script> -->

    <!-- Morris.js charts -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script> -->
    <script src="{{asset('plugins/morris/morris.min.js')}}"></script>
    <!-- Sparkline -->
    <script src="{{asset('plugins/sparkline/jquery.sparkline.min.js')}}"></script>
    <!-- jvectormap -->
    <script src="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
    <script src="{{asset('plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{asset('plugins/knob/jquery.knob.js')}}"></script>

    <!-- daterangepicker -->
    <script src="{{asset('js/moment/moment.min.js')}}"></script>
    <script src="{{asset('js/moment/es.js')}}"></script>
    <script src="{{asset('plugins/daterangepicker/daterangepicker.js')}}"></script>

    <!-- datepicker -->
    <script src="{{asset('plugins/datepicker/bootstrap-datepicker.js')}}"></script>

    <!-- Bootstrap WYSIHTML5 -->
    {{--<script src="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>--}}
    <!-- Slimscroll -->
    <script src="{{asset('plugins/slimScroll/jquery.slimscroll.min.js')}}"></script>
    <!-- FastClick -->
    <script src="{{asset('plugins/fastclick/fastclick.js')}}"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{{asset('js/dashboard.js')}}"></script>
    <!-- AdminLTE for demo purposes -->
    {{--<script src="dist/js/demo.js"></script>--}}
@endpush

resources/views/pregunta/show.blade.php
@extends('layouts.app')

@section('htmlheader_title')
	ver los resultado de la consulta 
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1 class="m-0 text-dark"> los resultado de la consulta  </h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->


    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">


                   
                    <div class="card">

                        <div class="card-body">
                          
                     
                                <!-- Card -->
                                <div class="card">
                                    <!-- Card image -->
                                    <!-- foto  -->
                                    <!-- Card content -->
                                    <div class="card-body">

                                    <!-- Title -->
                                    <h4 class="card-title" style=" text-transform: uppercase;"><a> {{ $pregunta }} </a></h4>
                                        <hr>
                                    <!-- Text -->
                                    @foreach ($ver as $key => $pre)
                                    <p class="card-text"> fecha de la consulta - {{ $pre['fecha'] }} </p>
                                    <span> {{ $pre['respuesta'] }} </span>
                                    <br>
                                    <hr>

                                    @endforeach


                                    </div>

                                </div>
                                <!-- Card -->

                     

                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->
           
                

            <div class="row">
                <div class="form-group col-sm-12">
                <a href="{!! route('pregunta.index') !!}" class="btn btn-default">Regresar</a>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection